<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Permisos {

	protected $rutas = [
		1 => [
			'productos/index',
			'productos/consulta',
			'productos/bajas',
			'proveedor/index',
			'clientes/index',
			'venta/index',
			'venta/nueva_venta',
			'venta/pedido',
			'devolucion/index',
			'devolucion/nueva_devolucion',
			'devolucion/pedido',
			'compra/index',
			'compra/crear_compra',
			'compra/pedido',
			'desecho/index',
			'desecho/nuevo_desecho',
			'desecho/pedido',
			'cobranza/clientes',
			'cobranza/index',
			'cobranza/abonos',
			'cobranza/doc_pendientes',
			'reportes/index',
			'reportes/inventario',
			'reportes/val_inv',
			'reportes/sin_exis',
			'reportes/stock_bajo',
			'reportes/sin_stock',
			'reportes/por_proveedor',
			'reportes/clasificacion',
			'flujo/index',
			'flujo/cortes',
			'flujo/corte',
			'flujo/reporte',
			'reportes/ventacobranza',
			'reportes/ventas',
			'reportes/ventas_marcas',
			'reportes/productos_vend',
			'reportes/prod_cant_vend',
			'reportes/prod_imp_vend',
			'reportes/calc',
			'reportes/por_debajo',
			'reportes/diff',
			'productos/actualiza_precios',
			'reportes/prec_act',
			'reportes/prod_act_prec',
			'reportes/prod_marcas',
			'historialproductos/index',
			'historialproductos/por_dia',
			'empresa/index',
			'folio/index',
			'dashboard/index',
			'reportes/config',
			'movsinv/index',
			'movsinv/kardex',
			'movsinv/conversion',
			'almacen/index',
			'templatetickets/index',
			'relacionados/index'
		],
		3 => [
			'productos/index',
			'productos/consulta',
			'productos/bajas',
			'proveedor/index',
			'clientes/index',
			'venta/index',
			'venta/nueva_venta',
			'venta/pedido',
			'devolucion/index',
			'devolucion/nueva_devolucion',
			'devolucion/pedido',
			'compra/index',
			'compra/crear_compra',
			'compra/pedido',
			'desecho/index',
			'desecho/nuevo_desecho',
			'desecho/pedido',
			'cobranza/clientes',
			'cobranza/index',
			'cobranza/abonos',
			'cobranza/doc_pendientes',
			'reportes/index',
			'reportes/inventario',
			'reportes/val_inv',
			'reportes/sin_exis',
			'reportes/stock_bajo',
			'reportes/sin_stock',
			'reportes/por_proveedor',
			'reportes/clasificacion',
			'flujo/index',
			'flujo/cortes',
			'flujo/corte',
			'flujo/reporte',
			'reportes/ventacobranza',
			'reportes/ventas',
			'reportes/ventas_marcas',
			'reportes/productos_vend',
			'reportes/prod_cant_vend',
			'reportes/prod_imp_vend',
			'reportes/calc',
			'reportes/por_debajo',
			'reportes/diff',
			'productos/actualiza_precios',
			'reportes/prec_act',
			'reportes/prod_act_prec',
			'reportes/prod_marcas',
			'historialproductos/index',
			'historialproductos/por_dia',
			'empresa/index',
			'dashboard/index',
			'movsinv/index',
			'movsinv/kardex',
			'movsinv/conversion',
		],
		4 => [
			'productos/consulta',
			'clientes/index',
			'venta/index',
			'venta/nueva_venta',
			'venta/pedido',
			'devolucion/index',
			'devolucion/nueva_devolucion',
			'devolucion/pedido',
			'cobranza/clientes',
			'cobranza/index',
			'cobranza/abonos',
			'reportes/calc',
		],
	];

	public function check($ruta, $grupo) {
		if(!in_array($ruta, $this->rutas[$grupo]))
			show_error('No posee los permisos necesarios.', 403, 'No permitido');
		
		return true;
	}


}
