name: Deploy to ECS

on:
push:
branches:
- develop

jobs:
deploy:
name: Build and Deploy
runs-on: ubuntu-latest


steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-2

  - name: Verify AWS Identity
    run: |
      aws sts get-caller-identity

  - name: Login to Amazon ECR
    uses: aws-actions/amazon-ecr-login@v2

  - name: Debug ECR
    run: |
      aws sts get-caller-identity
      aws ecr describe-repositories --region us-east-2

  - name: Build and Push PHP image
    run: |
      docker build -t 159858924500.dkr.ecr.us-east-2.amazonaws.com/inventory-php:latest -f docker/php/Dockerfile .
      docker push 159858924500.dkr.ecr.us-east-2.amazonaws.com/inventory-php:latest

  - name: Build and Push NGINX image
    run: |
      docker build -t 159858924500.dkr.ecr.us-east-2.amazonaws.com/inventory-nginx:latest -f docker/nginx/Dockerfile .
      docker push 159858924500.dkr.ecr.us-east-2.amazonaws.com/inventory-nginx:latest

  - name: Debug Docker Images
    run: |
      docker images

  - name: Force ECS deployment
    run: |
      aws ecs update-service \
        --cluster syslac-cluster \
        --service syslac-service \
        --force-new-deployment


